name: React build apple

######### master branch에 push 되었을때만 실행#########
on: 
  push:            
    branches:
      - master
######### master branch에 push 되었을때만 실행#########

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4        
        with:
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  
          echo "테스트 출력"
  
            
